version: '3'

services:
  elrond-bridge:
    image: elrond-bridge
    restart: always
    volumes:
      - './data:/usr/src/elrond-bridge/data'
    ports:
      - 9848:8848
    environment:
      - TZ=Asia/Shanghai
      - MAINNET_CHAIN_ENDPOINT=xx
      - LATESTBLOCK=xx
      - DESTID=100
      - SECTIONMETHOD=chainBridge.FungibleTransfer